// The coach's grounding: the bundled 48-day program content.
// coach-content.json is generated by scripts/app-content/build-content.ts —
// do not edit by hand.
import content from "@/data/coach-content.json";
import { scoreMemory } from "./memory";

export type DayLesson = { day: number; title: string; description: string; tags: string[]; body: string };

const DAYS: DayLesson[] = (content as { days: DayLesson[] }).days;
export const TOTAL_DAYS = DAYS.length;

export function getDayLesson(day: number): DayLesson | null {
  return DAYS.find((d) => d.day === day) ?? null;
}

/** Top-3 lessons matching the query (title/description/tags weighted over body). */
export function searchProtocols(query: string): Array<Omit<DayLesson, "body"> & { excerpt: string }> {
  const q = query.trim();
  if (!q) return [];
  return DAYS.map((d) => ({
    d,
    s: 3 * scoreMemory(`${d.title} ${d.description} ${d.tags.join(" ")}`, q) + scoreMemory(d.body, q),
  }))
    .filter((x) => x.s > 0)
    .sort((a, b) => b.s - a.s)
    .slice(0, 3)
    .map(({ d }) => ({ day: d.day, title: d.title, description: d.description, tags: d.tags, excerpt: d.body.slice(0, 400) }));
}
