// Shared types for optional per-segment narration audio, generated by
// voiceover.ts and consumed by ShortVideo.tsx / render-queue.ts.

// Word-level timestamp within a segment's audio clip, in seconds from the
// clip's start. Produced by forced alignment in scripts/voiceover/generate.py
// (<segment>.json sidecar); used to drive the word-synced caption highlight.
export type WordTiming = {
  word: string;
  start: number;
  end: number;
};

export type AudioSegment = {
  // Path relative to remotion/public, for use with staticFile().
  src: string;
  durationInFrames: number;
  // Present when generate.py produced a <segment>.json alignment sidecar.
  words?: WordTiming[];
};

export type ShortAudio = {
  hook: AudioSegment;
  captions: AudioSegment[];
  cta: AudioSegment;
};

// Optional recurring illustrated character (custom Tier 3 art, generated
// once by scripts/character/generate.py), opted into per queue item via a
// `character` field. `scenes` is one entry per caption, in the same order
// as splitIntoCaptions(script).
export type CharacterPose =
  | 'BlazerWB'
  | 'CrossedArmsWB'
  | 'EasingWB'
  | 'PointingFingerWB'
  | 'RestingWB'
  | 'RoboDanceWB'
  | 'ShirtWB'
  | 'WalkingWB';
export type CharacterExpression = 'Driven' | 'Calm' | 'Smile';

export type CharacterScene = {
  pose: CharacterPose;
  face: CharacterExpression;
};

export type CharacterConfig = {
  hook: CharacterScene;
  scenes: CharacterScene[];
  cta: CharacterScene;
};
