// Shared types for optional per-segment narration audio, generated by
// voiceover.ts and consumed by ShortVideo.tsx / render-queue.ts.

export type AudioSegment = {
  // Path relative to remotion/public, for use with staticFile().
  src: string;
  durationInFrames: number;
};

export type ShortAudio = {
  hook: AudioSegment;
  captions: AudioSegment[];
  cta: AudioSegment;
};
