// Reads the committed per-segment narration for a short (generated by
// scripts/voiceover/generate.py in Giannis's cloned voice) and measures each
// clip's duration so the render can size each Sequence to its narration.
//
// Narration is generated once by the Voiceover Generator workflow and
// committed under remotion/public/audio/<id>/. If an item has no audio yet,
// loadAudio() returns null and the render falls back to the silent,
// text-timed layout — so rendering never depends on the voiceover existing.

import fs from 'fs';
import path from 'path';
import {parseFile} from 'music-metadata';
import {splitIntoCaptions} from './splitScript';
import type {AudioSegment, ShortAudio} from './types';

type Item = {id: string; hook: string; script: string; cta: string};

async function measure(
  filePath: string,
  relPath: string,
  fps: number,
): Promise<AudioSegment> {
  const {format} = await parseFile(filePath);
  if (!format.duration) {
    throw new Error(`Could not determine duration of ${filePath}`);
  }
  return {src: relPath, durationInFrames: Math.ceil(format.duration * fps)};
}

export async function loadAudio(
  item: Item,
  publicDir: string,
  fps: number,
): Promise<ShortAudio | null> {
  const captionNames = splitIntoCaptions(item.script).map((_, i) => `caption-${i}`);
  const names = ['hook', ...captionNames, 'cta'];
  const exists = names.every((n) =>
    fs.existsSync(path.join(publicDir, 'audio', item.id, `${n}.mp3`)),
  );
  if (!exists) return null;

  const seg = (n: string) =>
    measure(
      path.join(publicDir, 'audio', item.id, `${n}.mp3`),
      path.posix.join('audio', item.id, `${n}.mp3`),
      fps,
    );

  return {
    hook: await seg('hook'),
    captions: await Promise.all(captionNames.map(seg)),
    cta: await seg('cta'),
  };
}
